# (generated with --quick)

from typing import List

class ChildClass(ParentClass):
    def __init__(self) -> None: ...
    def my_function(self) -> List[int]: ...

class ParentClass:
    def __init__(self) -> None: ...
    def my_function(self) -> List[int]: ...
