GROUND_TRUTH = {
    "case1_static": [
        "<builtin>.len",
        "random.choices",
        "<builtin>.any",
        "<builtin>.all",
        "<builtin>.print",
    ],
    "case1_dynamic": [
        "<builtin>.len",
        "random.Random.choices",
        "<builtin>.any",
        "<builtin>.all",
        "<builtin>.print",
    ],
    "case2_static": [
        "math.factorial",
        "datetime.datetime.now",
        "math.ceil",
        "json.dumps",
        "math.sqrt",
        "to_import.call_funcs",
    ],
    "case2_dynamic": [
        "math.factorial",
        "datetime.datetime.now",
        "math.ceil",
        "json.dumps",
        "math.sqrt",
        "to_import.call_funcs",
    ],
    "case3_static": [
        "case3.sum_list_items.do_the_sum",
        "case3.sum_list_items.do_the_sum.do_core_computations",
        "case3.sum_list_items",
        "random.choices",
        "<builtin>.len",
    ],
    "case3_dynamic": [
        "case3.sum_list_items.do_the_sum",
        "case3.sum_list_items.do_the_sum.do_core_computations",
        "case3.sum_list_items",
        "random.Random.choices",
        "<builtin>.len",
    ],
    "external_lib_test_static": [
        "seaborn.load_dataset",
        "pandas.read_csv",
        "keras.models.Sequential",
        "matplotlib.pyplot.figure",
        "seaborn.countplot",
    ],
    "external_lib_test_dynamic": [
        "pandas.io.parsers.readers.read_csv",
        "seaborn.categorical.countplot",
        "matplotlib.pyplot.figure",
        "keras.models.Sequential",
        "seaborn.utils.load_dataset",
    ],
}
